version: 2

sources:
    - name: jaffle_shop
      schema: my_dbt_db

      tables:
        - name: raw_customers
        - name: raw_orders
        - name: raw_items
        - name: raw_products
        - name: raw_stores
        - name: raw_supplies
